language: android

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          env: DIST=gce-trusty
        - os: linux
          sudo: false
          dist: trusty
          env: DIST=ec2-trusty
        - os: linux
          sudo: required
          dist: precise
          env: DIST=gce-precise
        - os: linux
          sudo: false
          dist: precise
          env: DIST=docker-precise

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-19.1.0
    # The SDK version used to compile your project
    - android-22

script:
  - echo hola
