sudo: required
language: generic

matrix:
  include:
    - dist: precise
    - dist: trusty

before_install:
- sudo rm -vf /etc/apt/sources.list.d/*riak*
- sudo apt-get update

services:
  - riak
  
install: true

script: echo hola
